wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.12.1
    cli_version: 0.17.5
    framework: huggingface
    huggingface_version: 4.41.0.dev0
    is_jupyter_run: true
    is_kaggle_kernel: true
    start_time: 1722600600
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      - 71
      - 105
      2:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      - 71
      - 105
      3:
      - 2
      - 13
      - 23
      4: 3.12.1
      5: 0.17.5
      6: 4.41.0.dev0
      8:
      - 1
      - 2
      - 5
      13: linux-x86_64
