wandb_version: 1

model:
  desc: null
  value: bert-base-multilingual-cased
lora_r:
  desc: null
  value: 16
lora_alpha:
  desc: null
  value: 32
lora_dropout:
  desc: null
  value: 0.1
learning_rate:
  desc: null
  value: 2.0e-05
batch_size:
  desc: null
  value: 16
num_epochs:
  desc: null
  value: 3
_wandb:
  desc: null
  value:
    python_version: 3.12.1
    cli_version: 0.17.5
    framework: huggingface
    huggingface_version: 4.41.0.dev0
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1722602786
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      - 71
      - 98
      - 105
      2:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      - 71
      - 98
      - 105
      3:
      - 13
      - 16
      - 23
      4: 3.12.1
      5: 0.17.5
      6: 4.41.0.dev0
      8:
      - 2
      - 5
      13: linux-x86_64
